name: iOS Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install Pods
        run: pod install

      - name: Build App
        run: fastlane build









